version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"

  - package-ecosystem: cargo
    directories:
      - /
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"
    allow:
      - dependency-type: direct
